version: '3.8'

services:
  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - app-network
  
 # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${RESTAURANT_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge