version: '3.8'

services:
  api-gateway:
      build: ./api-gateway
      container_name: api-gateway
      ports:
        - "8000:8000"
      environment:
        - API_GATEWAY_PORT=8000
        - AUTH_SERVICE=http://auth-service:8001
        - RESTAURANT_SERVICE=http://restaurant-service:5000
        - ORDER_SERVICE=http://order-service:5001
        - PAYMENT_SERVICE=http://payment-service:5003
        - DELIVERY_SERVICE=http://delivery-service:8080
        - JWT_SECRET=${JWT_SECRET}
      depends_on:
        - auth-service
        - restaurant-service
        - order-service
        - payment-service
        - delivery-service
      networks:
        - app-network
        
  # Auth Service
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    networks:
      - app-network
  
  # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    container_name: restaurant-service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${RESTAURANT_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
  # Order Service
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - ORDER_MONGO_URI=${ORDER_MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  # Payment Service
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "5003:5003"
    environment:
      - PORT=5003
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    networks:
      - app-network
      
  # Delivery Service
  delivery-service:
    build: ./delivery-service
    container_name: delivery-service
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ServiceUrls__AuthService=http://auth-service:8000
      - ServiceUrls__RestaurantService=http://restaurant-service:5000
      - ServiceUrls__OrderService=http://order-service:5001
      - DatabaseSettings__ConnectionString=${DELIVERY_MONGO_URI}
    networks:
    - app-network

networks:
  app-network:
    driver: bridge